-- Drag-and-drop "Lego builder" core (/builder-blocks) -- a new, separate
-- product surface from the existing prompt-driven AI builder at /builder
-- (LinearBuilderClient.tsx). Confirmed with the user this lives at its own
-- route rather than replacing /builder. Its own table rather than reusing
-- `projects` (db/migrations/0001_init.sql, which stores a single `html`
-- blob generated by the AI builder) because a block-builder project is
-- structured data -- an ordered tree of typed blocks with props -- that
-- needs to be read back and re-edited visually, not just displayed as a
-- final HTML string. `blocks` stores that tree as jsonb; the generated
-- code (lib/builderBlocks/codeGenerator.ts) is derived from it on demand
-- rather than persisted, so there's one source of truth to edit.
-- Safe to re-run: IF NOT EXISTS throughout.
create table if not exists builder_block_projects (
  id         uuid primary key default gen_random_uuid(),
  user_id    text not null,
  name       text not null default 'Untitled',
  blocks     jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists builder_block_projects_user_id_updated_at_idx
  on builder_block_projects (user_id, updated_at desc);
