import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.gysm.io";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "GYSM - AI Website Builder | Build in 30 seconds",
  description:
    "Describe the app you want and GYSM builds it — a working, previewable website generated by AI in seconds, ready to export or deploy.",
  openGraph: {
    title: "GYSM - AI Website Builder | Build in 30 seconds",
    description: "Describe the app you want and GYSM builds it in seconds.",
    url: siteUrl,
    siteName: "GYSM.IO",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "GYSM - AI Website Builder | Build in 30 seconds",
    description: "Describe the app you want and GYSM builds it in seconds.",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}